#
# YAML Anchors
#


x-common: &common
  env_file: secrets.env

x-ports:
  - &files-port "8001"
  - &games-port "8002"
  - &auth-port  "8003"
  - &users-port "8004"

x-urls:
  - &files-url http://files-service:8001
  - &games-url http://games-service:8002
  - &auth-url  http://auth-service:8003
  - &users-url http://users-service:8004
  - &mongo-url mongodb://mongo:27017

x-dbs:
  - &games-db games
  - &users-db users
  - &auth-db  auth


#
# Services
#


services:
  gateway:
    <<: *common
    build:
      context: ./services/gateway
    ports:
      - "8000:8000"
    environment:
      FILES_SERVICE_URL: *files-url
      GAMES_SERVICE_URL: *games-url
      AUTH_SERVICE_URL:  *auth-url
      USERS_SERVICE_URL: *users-url
    depends_on:
      - games-service
      - auth-service
      - files-service
      - users-service
    networks:
      - internal
      - public

  files-service:
    <<: *common
    build:
      context: ./services/files
    networks:
      - internal
    environment:
      PORT: *files-port

  users-service:
    <<: *common
    build:
      context: ./services
      dockerfile: ./userService/Dockerfile
    networks:
      - internal
    environment:
      PORT:    *users-port
      DB_URL:  *mongo-url
      DB_NAME: *users-db
    depends_on:
      mongo:
        condition: service_healthy

  games-service:
    <<: *common
    build:
      context: ./services
      dockerfile: ./gameService/Dockerfile
    networks:
      - internal
    environment:
      PORT:              *games-port
      DB_URL:            *mongo-url
      DB_NAME:           *games-db
      USERS_SERVICE_URL: *users-url
    depends_on:
      mongo:
        condition: service_healthy

  auth-service:
    <<: *common
    build:
      context: ./services
      dockerfile: ./auth/Dockerfile
    networks:
      - internal
    environment:
      PORT:              *auth-port
      JWT_SECRET:        ${JWT_SECRET}
      ACCESS_TOKEN_EXPIRY:      ${ACCESS_TOKEN_EXPIRY}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}
      DB_URL:            *mongo-url
      DB_NAME:           *auth-db
      USERS_SERVICE_URL: *users-url
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    <<: *common
    image: mongo:7.0
    volumes:
      - ./data/db:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    <<: *common
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL:        *mongo-url
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - internal
      - public


#
# Networks
#


networks:
  public:
  internal:
    internal: true
