services:
  gateway:
    build:
      context:
        ./services/gateway
    ports:
      - "8000:8000"
    environment:
      GAME_SERVICE_URL: http://game-service:8002
      FILE_SERVICE_URL: http://files-service:8001
      AUTH_SERVICE_URL: http://auth-service:8003
    depends_on:
      - game-service
      - auth-service
      - files-service
    networks:
      - internal
      - public

  files-service:
    build:
      context: ./services/files
    networks:
      - internal

  game-service:
    build:
      context: ./services
      dockerfile: ./gameService/Dockerfile
    networks:
      - internal

  auth-service:
    build:
      context: ./services
      dockerfile: ./auth/Dockerfile
    networks:
      - internal
    environment:
      DB_URL: mongodb://mongo:27017
      DB_NAME : ps8
      JWT_SECRET : kSMIWOZ2BOEAqbnwGLXafltUn1yO2iE5wkeN6h81m4Q=
    depends_on:
      - mongo

  mongo:
    image : mongo:latest
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    networks:
      - internal

  mongo-express: # image utilisée pour monitor la db depuis un navigateur
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - internal
      - public


networks:
  public:
  internal:
    internal: true



