#
# YAML Anchors
#


x-common: &common
  env_file: secrets.env

x-ports:
  - &files-port "8001"
  - &games-port "8002"
  - &auth-port  "8003"
  - &users-port "8004"
  - &challenge-port "8005"

x-urls:
  - &files-url http://file-service:8001
  - &games-url http://game-service:8002
  - &auth-url  http://auth-service:8003
  - &users-url http://user-service:8004
  - &mongo-url mongodb://mongo:27017
  - &challenge-url http://challenge-service:8005

x-dbs:
  - &games-db games
  - &users-db users
  - &auth-db  auth


#
# Services
#


services:
  gateway:
    <<: *common
    build:
      context: ./services/gateway
    depends_on:
      - game-service
      - auth-service
      - file-service
      - user-service
      - challenge-service
    environment:
      IS_PROD: ${IS_PROD}
      FILE_SERVICE_URL: *files-url
      GAME_SERVICE_URL: *games-url
      AUTH_SERVICE_URL: *auth-url
      USER_SERVICE_URL: *users-url
      SSL_CERTIFICATE: ${SSL_CERTIFICATE}
      SSL_PRIVATE_KEY: ${SSL_PRIVATE_KEY}
    ports:
      - "8000:8000"
    networks:
      - internal
      - public

  file-service:
    <<: *common
    build:
      context: ./services/files
    environment:
      PORT: *files-port
    volumes:
      - ./frontend/src:/app/front
      - ./frontend/assets:/app/front/assets
    networks:
      - internal

  user-service:
    <<: *common
    build:
      context: ./services
      dockerfile: ./userService/Dockerfile
    networks:
      - internal
    environment:
      PORT:    *users-port
      DB_URL:  *mongo-url
      DB_NAME: *users-db
    depends_on:
      mongo:
        condition: service_healthy

  game-service:
    <<: *common
    build:
      context: ./services
      dockerfile: ./gameService/Dockerfile
    networks:
      - internal
    environment:
      PORT:             *games-port
      DB_URL:           *mongo-url
      DB_NAME:          *games-db
      USER_SERVICE_URL: *users-url
    depends_on:
      mongo:
        condition: service_healthy

  challenge-service:
    <<: *common
    build:
      context: ./services
      dockerfile: ./challengeService/Dockerfile
    networks:
      - internal
    environment:
      PORT: *challenge-port
      USER_SERVICE_URL: *users-url
      GAME_SERVICE_URL: *games-url

  auth-service:
    <<: *common
    build:
      context: ./services
      dockerfile: ./auth/Dockerfile
    environment:
      PORT:                 *auth-port
      JWT_SECRET:           ${JWT_SECRET}
      ACCESS_TOKEN_EXPIRY:  ${ACCESS_TOKEN_EXPIRY}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}
      DB_URL:               *mongo-url
      DB_NAME:              *auth-db
      USER_SERVICE_URL:     *users-url
    networks:
      - internal

  mongo:
    <<: *common
    image: mongo:7.0
    volumes:
      - ./data/db:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    <<: *common
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL:        *mongo-url
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - internal
      - public


#
# Networks
#


networks:
  public:
  internal:
    internal: true
