services:
  gateway:
    build:
      context:
        ./services/gateway
    ports:
      - "8000:8000"
    environment:
      FILES_SERVICE_URL: http://files-service:8001
      GAMES_SERVICE_URL: http://games-service:8002
      AUTH_SERVICE_URL: http://auth-service:8003
    depends_on:
      - files-service
      - games-service
      - auth-service
    networks:
      - internal
      - public

  files-service:
    build:
      context: ./services/files
    networks:
      - internal

  games-service:
    build:
      context: ./services
      dockerfile: ./gameService/Dockerfile
    networks:
      - internal

  auth-service:
    build:
      context: ./services
      dockerfile: ./auth/Dockerfile
    networks:
      - internal
    environment:
      DB_URL: mongodb://mongo:27017
      DB_NAME : ps8
      JWT_SECRET : kSMIWOZ2BOEAqbnwGLXafltUn1yO2iE5wkeN6h81m4Q=
    depends_on:
      - mongo

  mongo:
    image : mongo:7.0
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express: # image utilisée pour monitor la db depuis un navigateur
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - internal
      - public


networks:
  public:
  internal:
    internal: true
